server:
  servlet:
    session:
      cookie:
        http-only: true
        secure: true
    context-path: /earthly

logging:
  level:
    root: debug
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    name: ${earthly.datasource.name}
    password: ${earthly.datasource.passowrd}
    url: ${earthly.datasource.url}
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      maximum-pool-size: 10

earthly:
  datasource:
    host: ${MYSQL_HOST:localhost}
    port: ${MYSQL_PORT:3306}
    name: ${MYSQL_USER_NAME:planets}
    passowrd: ${MYSQL_USER_PASSWORD:planets}
    schema: ${MYSQL_SCHEMA:planets}
    url: jdbc:mysql:${earthly.datasource.host}:${earthly.datasource.port}/${earthly.datasource.schema}?useSSL=false